akkasample {
    some-dispatcher {
        type = Dispatcher
        executor = "thread-pool-executor"
        thread-pool-executor {
            core-pool-size-min = 2
            core-pool-size-max = 5
        }
    }
}