spring:
  kafka:
    bootstrap-servers: kafka:29092,kafka2:29093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    test-topic: topic1